### PR TITLE
Add team, channel, and user attributes to New Relic traces

### PR DESCRIPTION
**Pull request by kstole**
@dblock how would you feel about including team, channel, and user in New Relic traces?

### CODE REVIEW

**Comment by dblock** [comment]
Love it. Needs tests, changelog, etc.

**Comment by kstole** [comment]
@dblock I'm not sure if there's a good way to really test that the attributes are sent to New Relic. That's more the job of the newrelic_rpm gem, so I think the tests here are good enough. What do you think?

**Comment by dblock** [comment]
I meant a test in which `NewRelic::Agent.add_custom_attributes` is called with the right parameters, which you clearly have now done, so this is good to go!

**Comment by dblock** [comment]
Btw, this could use some new screenshots to the README, maybe a note that the gem does that ;)

**Pull request merged**
